import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {pages} from '../site/pages.mjs';
import {header,footer} from '../site/shared.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const escapeAttr = value => value.replaceAll('&','&amp;').replaceAll('"','&quot;');
let changed = 0;
async function write(name, content) {
  const destination = path.join(root,name);
  const existing = await fs.readFile(destination,'utf8').catch(()=> '');
  if (existing.replaceAll('\r\n','\n') === content) return;
  changed++;
  if (check) throw new Error(`Generated page is stale: ${name}. Run npm run build.`);
  await fs.writeFile(destination,content);
  console.log(`Updated ${name}`);
}
for (const page of pages) {
  const title = `${page.title}｜タケノコ`;
  await write(page.file, `<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#263e30">
  <title>${title}</title>
  <meta name="description" content="${escapeAttr(page.description)}">
  <link rel="canonical" href="https://takenokonoko.com/${page.file}">
  <meta property="og:type" content="website">
  <meta property="og:locale" content="ja_JP">
  <meta property="og:title" content="${escapeAttr(title)}">
  <meta property="og:description" content="${escapeAttr(page.description)}">
  <meta property="og:url" content="https://takenokonoko.com/${page.file}">
  <link rel="icon" href="assets/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="assets/home.css">
  <link rel="stylesheet" href="assets/site.css">
  <script src="assets/home.js" defer></script>
</head>
<body class="subpage${page.policy?' policy-page':''}">
  <!-- Generated by scripts/build_pages.mjs. Edit site/pages.mjs or site/policies.mjs. -->
  <a class="skip-link" href="#main">本文へ移動</a>
  ${header()}
  <main id="main">
    <div class="container breadcrumb"><a href="index.html">トップ</a><span aria-hidden="true">/</span><span>${page.title}</span></div>
    <section class="sub-hero"><div class="container"><p class="eyebrow">${page.eyebrow}</p><h1>${page.heading}</h1><p class="sub-lead">${page.description}</p>${page.policy?'':'<a class="text-link" href="index.html#contact">この業務について相談する <span aria-hidden="true">↗</span></a>'}</div></section>
    ${page.body}
  </main>
  ${footer()}
</body>
</html>
`);
}
// Keep the hand-authored home page, replacing only the shared navigation/footer.
const home = await fs.readFile(path.join(root,'index.html'),'utf8');
const refreshedHome = home
  .replace(/<header class="site-header">[\s\S]*?<\/header>/,header(true))
  .replace(/<footer class="site-footer">[\s\S]*?<\/footer>/,footer(true));
await write('index.html',refreshedHome.replaceAll('\r\n','\n'));
await write('index.dc.html', `<!doctype html>
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,follow"><link rel="canonical" href="https://takenokonoko.com/"><meta http-equiv="refresh" content="0;url=index.html"><title>タケノコ｜現行ページへ移動</title></head><body><p>参考デザインは現行ページに統合しました。<a href="index.html">タケノコのトップページへ</a></p></body></html>
`);
console.log(check ? 'All generated pages are current.' : `Build complete (${changed} files updated).`);
